//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Метаданные связи EDM

[assembly: EdmRelationshipAttribute("KazMap.DataAccess", "FK_Intersection_NODE", "Nodes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(KazMap.DataAccess.Nodes), "Intersections", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KazMap.DataAccess.Intersections), true)]
[assembly: EdmRelationshipAttribute("KazMap.DataAccess", "FK_Path_Left", "Intersections", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(KazMap.DataAccess.Intersections), "Path", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KazMap.DataAccess.Path), true)]
[assembly: EdmRelationshipAttribute("KazMap.DataAccess", "FK_Path_Right", "Intersections", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(KazMap.DataAccess.Intersections), "Path", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KazMap.DataAccess.Path), true)]
[assembly: EdmRelationshipAttribute("KazMap.DataAccess", "FK_NodeTAG_NODE", "Nodes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(KazMap.DataAccess.Nodes), "NodeTags", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KazMap.DataAccess.NodeTags), true)]
[assembly: EdmRelationshipAttribute("KazMap.DataAccess", "FK_Path_LeftNode", "Nodes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(KazMap.DataAccess.Nodes), "Path", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KazMap.DataAccess.Path), true)]
[assembly: EdmRelationshipAttribute("KazMap.DataAccess", "FK_Path_RightNode", "Nodes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(KazMap.DataAccess.Nodes), "Path", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KazMap.DataAccess.Path), true)]
[assembly: EdmRelationshipAttribute("KazMap.DataAccess", "FK_WayNODE_NODE", "Nodes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(KazMap.DataAccess.Nodes), "WayNodes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KazMap.DataAccess.WayNodes), true)]
[assembly: EdmRelationshipAttribute("KazMap.DataAccess", "FK_NodeTAG_TagType", "TagTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(KazMap.DataAccess.TagTypes), "NodeTags", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KazMap.DataAccess.NodeTags), true)]
[assembly: EdmRelationshipAttribute("KazMap.DataAccess", "FK_Path_Road", "Roads", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(KazMap.DataAccess.Roads), "Path", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KazMap.DataAccess.Path), true)]
[assembly: EdmRelationshipAttribute("KazMap.DataAccess", "FK_RelNODE_Relation", "Relations", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(KazMap.DataAccess.Relations), "RelationNodes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KazMap.DataAccess.RelationNodes), true)]
[assembly: EdmRelationshipAttribute("KazMap.DataAccess", "FK_RelTAG_Relation", "Relations", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(KazMap.DataAccess.Relations), "RelationTags", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KazMap.DataAccess.RelationTags), true)]
[assembly: EdmRelationshipAttribute("KazMap.DataAccess", "FK_RelTAG_TagType", "TagTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(KazMap.DataAccess.TagTypes), "RelationTags", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KazMap.DataAccess.RelationTags), true)]
[assembly: EdmRelationshipAttribute("KazMap.DataAccess", "FK_Road_Way", "Ways", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(KazMap.DataAccess.Ways), "Roads", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KazMap.DataAccess.Roads), true)]
[assembly: EdmRelationshipAttribute("KazMap.DataAccess", "FK_WayTAG_TagType", "TagTypes", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(KazMap.DataAccess.TagTypes), "WayTags", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KazMap.DataAccess.WayTags), true)]
[assembly: EdmRelationshipAttribute("KazMap.DataAccess", "FK_WayNODE_Way", "Ways", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(KazMap.DataAccess.Ways), "WayNodes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KazMap.DataAccess.WayNodes), true)]
[assembly: EdmRelationshipAttribute("KazMap.DataAccess", "FK_WayTAG_Way", "Ways", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(KazMap.DataAccess.Ways), "WayTags", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(KazMap.DataAccess.WayTags), true)]

#endregion

namespace KazMap.DataAccess
{
    #region Контексты
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    public partial class KazMapConnection : ObjectContext
    {
        #region Конструкторы
    
        /// <summary>
        /// Инициализирует новый объект KazMapConnection, используя строку соединения из раздела "KazMapConnection" файла конфигурации приложения.
        /// </summary>
        public KazMapConnection() : base("name=KazMapConnection", "KazMapConnection")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта KazMapConnection.
        /// </summary>
        public KazMapConnection(string connectionString) : base(connectionString, "KazMapConnection")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта KazMapConnection.
        /// </summary>
        public KazMapConnection(EntityConnection connection) : base(connection, "KazMapConnection")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Разделяемые методы
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Свойства ObjectSet
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Intersections> Intersections
        {
            get
            {
                if ((_Intersections == null))
                {
                    _Intersections = base.CreateObjectSet<Intersections>("Intersections");
                }
                return _Intersections;
            }
        }
        private ObjectSet<Intersections> _Intersections;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Nodes> Nodes
        {
            get
            {
                if ((_Nodes == null))
                {
                    _Nodes = base.CreateObjectSet<Nodes>("Nodes");
                }
                return _Nodes;
            }
        }
        private ObjectSet<Nodes> _Nodes;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<NodeTags> NodeTags
        {
            get
            {
                if ((_NodeTags == null))
                {
                    _NodeTags = base.CreateObjectSet<NodeTags>("NodeTags");
                }
                return _NodeTags;
            }
        }
        private ObjectSet<NodeTags> _NodeTags;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Path> Path
        {
            get
            {
                if ((_Path == null))
                {
                    _Path = base.CreateObjectSet<Path>("Path");
                }
                return _Path;
            }
        }
        private ObjectSet<Path> _Path;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<RelationNodes> RelationNodes
        {
            get
            {
                if ((_RelationNodes == null))
                {
                    _RelationNodes = base.CreateObjectSet<RelationNodes>("RelationNodes");
                }
                return _RelationNodes;
            }
        }
        private ObjectSet<RelationNodes> _RelationNodes;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Relations> Relations
        {
            get
            {
                if ((_Relations == null))
                {
                    _Relations = base.CreateObjectSet<Relations>("Relations");
                }
                return _Relations;
            }
        }
        private ObjectSet<Relations> _Relations;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<RelationTags> RelationTags
        {
            get
            {
                if ((_RelationTags == null))
                {
                    _RelationTags = base.CreateObjectSet<RelationTags>("RelationTags");
                }
                return _RelationTags;
            }
        }
        private ObjectSet<RelationTags> _RelationTags;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Roads> Roads
        {
            get
            {
                if ((_Roads == null))
                {
                    _Roads = base.CreateObjectSet<Roads>("Roads");
                }
                return _Roads;
            }
        }
        private ObjectSet<Roads> _Roads;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<TagTypes> TagTypes
        {
            get
            {
                if ((_TagTypes == null))
                {
                    _TagTypes = base.CreateObjectSet<TagTypes>("TagTypes");
                }
                return _TagTypes;
            }
        }
        private ObjectSet<TagTypes> _TagTypes;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<WayNodes> WayNodes
        {
            get
            {
                if ((_WayNodes == null))
                {
                    _WayNodes = base.CreateObjectSet<WayNodes>("WayNodes");
                }
                return _WayNodes;
            }
        }
        private ObjectSet<WayNodes> _WayNodes;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Ways> Ways
        {
            get
            {
                if ((_Ways == null))
                {
                    _Ways = base.CreateObjectSet<Ways>("Ways");
                }
                return _Ways;
            }
        }
        private ObjectSet<Ways> _Ways;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<WayTags> WayTags
        {
            get
            {
                if ((_WayTags == null))
                {
                    _WayTags = base.CreateObjectSet<WayTags>("WayTags");
                }
                return _WayTags;
            }
        }
        private ObjectSet<WayTags> _WayTags;

        #endregion
        #region Методы AddTo
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Intersections. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToIntersections(Intersections intersections)
        {
            base.AddObject("Intersections", intersections);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Nodes. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToNodes(Nodes nodes)
        {
            base.AddObject("Nodes", nodes);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet NodeTags. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToNodeTags(NodeTags nodeTags)
        {
            base.AddObject("NodeTags", nodeTags);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Path. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToPath(Path path)
        {
            base.AddObject("Path", path);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet RelationNodes. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToRelationNodes(RelationNodes relationNodes)
        {
            base.AddObject("RelationNodes", relationNodes);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Relations. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToRelations(Relations relations)
        {
            base.AddObject("Relations", relations);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet RelationTags. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToRelationTags(RelationTags relationTags)
        {
            base.AddObject("RelationTags", relationTags);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Roads. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToRoads(Roads roads)
        {
            base.AddObject("Roads", roads);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet TagTypes. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToTagTypes(TagTypes tagTypes)
        {
            base.AddObject("TagTypes", tagTypes);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet WayNodes. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToWayNodes(WayNodes wayNodes)
        {
            base.AddObject("WayNodes", wayNodes);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Ways. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToWays(Ways ways)
        {
            base.AddObject("Ways", ways);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet WayTags. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToWayTags(WayTags wayTags)
        {
            base.AddObject("WayTags", wayTags);
        }

        #endregion
    }
    

    #endregion
    
    #region Сущности
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KazMap.DataAccess", Name="Intersections")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Intersections : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Intersections.
        /// </summary>
        /// <param name="id">Исходное значение свойства Id.</param>
        public static Intersections CreateIntersections(global::System.Int64 id)
        {
            Intersections intersections = new Intersections();
            intersections.Id = id;
            return intersections;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> NodeId
        {
            get
            {
                return _NodeId;
            }
            set
            {
                OnNodeIdChanging(value);
                ReportPropertyChanging("NodeId");
                _NodeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NodeId");
                OnNodeIdChanged();
            }
        }
        private Nullable<global::System.Int64> _NodeId;
        partial void OnNodeIdChanging(Nullable<global::System.Int64> value);
        partial void OnNodeIdChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_Intersection_NODE", "Nodes")]
        public Nodes Node
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nodes>("KazMap.DataAccess.FK_Intersection_NODE", "Nodes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nodes>("KazMap.DataAccess.FK_Intersection_NODE", "Nodes").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Nodes> NodeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nodes>("KazMap.DataAccess.FK_Intersection_NODE", "Nodes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Nodes>("KazMap.DataAccess.FK_Intersection_NODE", "Nodes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KazMap.DataAccess", Name="Nodes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Nodes : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Nodes.
        /// </summary>
        /// <param name="id">Исходное значение свойства Id.</param>
        public static Nodes CreateNodes(global::System.Int64 id)
        {
            Nodes nodes = new Nodes();
            nodes.Id = id;
            return nodes;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private Nullable<global::System.Double> _Longitude;
        partial void OnLongitudeChanging(Nullable<global::System.Double> value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private Nullable<global::System.Double> _Latitude;
        partial void OnLatitudeChanging(Nullable<global::System.Double> value);
        partial void OnLatitudeChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_NodeTAG_NODE", "NodeTags")]
        public EntityCollection<NodeTags> Tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NodeTags>("KazMap.DataAccess.FK_NodeTAG_NODE", "NodeTags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NodeTags>("KazMap.DataAccess.FK_NodeTAG_NODE", "NodeTags", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KazMap.DataAccess", Name="NodeTags")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NodeTags : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта NodeTags.
        /// </summary>
        /// <param name="id">Исходное значение свойства Id.</param>
        public static NodeTags CreateNodeTags(global::System.Int64 id)
        {
            NodeTags nodeTags = new NodeTags();
            nodeTags.Id = id;
            return nodeTags;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> NodeId
        {
            get
            {
                return _NodeId;
            }
            set
            {
                OnNodeIdChanging(value);
                ReportPropertyChanging("NodeId");
                _NodeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NodeId");
                OnNodeIdChanged();
            }
        }
        private Nullable<global::System.Int64> _NodeId;
        partial void OnNodeIdChanging(Nullable<global::System.Int64> value);
        partial void OnNodeIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> TypeId
        {
            get
            {
                return _TypeId;
            }
            set
            {
                OnTypeIdChanging(value);
                ReportPropertyChanging("TypeId");
                _TypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TypeId");
                OnTypeIdChanged();
            }
        }
        private Nullable<global::System.Int64> _TypeId;
        partial void OnTypeIdChanging(Nullable<global::System.Int64> value);
        partial void OnTypeIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_NodeTAG_NODE", "Nodes")]
        public Nodes Node
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nodes>("KazMap.DataAccess.FK_NodeTAG_NODE", "Nodes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nodes>("KazMap.DataAccess.FK_NodeTAG_NODE", "Nodes").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Nodes> NodeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nodes>("KazMap.DataAccess.FK_NodeTAG_NODE", "Nodes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Nodes>("KazMap.DataAccess.FK_NodeTAG_NODE", "Nodes", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_NodeTAG_TagType", "TagTypes")]
        public TagTypes Type
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TagTypes>("KazMap.DataAccess.FK_NodeTAG_TagType", "TagTypes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TagTypes>("KazMap.DataAccess.FK_NodeTAG_TagType", "TagTypes").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TagTypes> TypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TagTypes>("KazMap.DataAccess.FK_NodeTAG_TagType", "TagTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TagTypes>("KazMap.DataAccess.FK_NodeTAG_TagType", "TagTypes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KazMap.DataAccess", Name="Path")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Path : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Path.
        /// </summary>
        /// <param name="id">Исходное значение свойства id.</param>
        public static Path CreatePath(global::System.Int64 id)
        {
            Path path = new Path();
            path.id = id;
            return path;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> LeftId
        {
            get
            {
                return _LeftId;
            }
            set
            {
                OnLeftIdChanging(value);
                ReportPropertyChanging("LeftId");
                _LeftId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LeftId");
                OnLeftIdChanged();
            }
        }
        private Nullable<global::System.Int64> _LeftId;
        partial void OnLeftIdChanging(Nullable<global::System.Int64> value);
        partial void OnLeftIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RightId
        {
            get
            {
                return _RightId;
            }
            set
            {
                OnRightIdChanging(value);
                ReportPropertyChanging("RightId");
                _RightId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RightId");
                OnRightIdChanged();
            }
        }
        private Nullable<global::System.Int64> _RightId;
        partial void OnRightIdChanging(Nullable<global::System.Int64> value);
        partial void OnRightIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Weight
        {
            get
            {
                return _Weight;
            }
            set
            {
                OnWeightChanging(value);
                ReportPropertyChanging("Weight");
                _Weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Weight");
                OnWeightChanged();
            }
        }
        private Nullable<global::System.Int32> _Weight;
        partial void OnWeightChanging(Nullable<global::System.Int32> value);
        partial void OnWeightChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RoadId
        {
            get
            {
                return _RoadId;
            }
            set
            {
                OnRoadIdChanging(value);
                ReportPropertyChanging("RoadId");
                _RoadId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoadId");
                OnRoadIdChanged();
            }
        }
        private Nullable<global::System.Int64> _RoadId;
        partial void OnRoadIdChanging(Nullable<global::System.Int64> value);
        partial void OnRoadIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> LeftNodeId
        {
            get
            {
                return _LeftNodeId;
            }
            set
            {
                OnLeftNodeIdChanging(value);
                ReportPropertyChanging("LeftNodeId");
                _LeftNodeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LeftNodeId");
                OnLeftNodeIdChanged();
            }
        }
        private Nullable<global::System.Int64> _LeftNodeId;
        partial void OnLeftNodeIdChanging(Nullable<global::System.Int64> value);
        partial void OnLeftNodeIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RightNodeId
        {
            get
            {
                return _RightNodeId;
            }
            set
            {
                OnRightNodeIdChanging(value);
                ReportPropertyChanging("RightNodeId");
                _RightNodeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RightNodeId");
                OnRightNodeIdChanged();
            }
        }
        private Nullable<global::System.Int64> _RightNodeId;
        partial void OnRightNodeIdChanging(Nullable<global::System.Int64> value);
        partial void OnRightNodeIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Distance
        {
            get
            {
                return _Distance;
            }
            set
            {
                OnDistanceChanging(value);
                ReportPropertyChanging("Distance");
                _Distance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Distance");
                OnDistanceChanged();
            }
        }
        private Nullable<global::System.Double> _Distance;
        partial void OnDistanceChanging(Nullable<global::System.Double> value);
        partial void OnDistanceChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_Path_Left", "Intersections")]
        public Intersections LeftIntersection
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Intersections>("KazMap.DataAccess.FK_Path_Left", "Intersections").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Intersections>("KazMap.DataAccess.FK_Path_Left", "Intersections").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Intersections> LeftIntersectionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Intersections>("KazMap.DataAccess.FK_Path_Left", "Intersections");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Intersections>("KazMap.DataAccess.FK_Path_Left", "Intersections", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_Path_Right", "Intersections")]
        public Intersections RightIntersection
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Intersections>("KazMap.DataAccess.FK_Path_Right", "Intersections").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Intersections>("KazMap.DataAccess.FK_Path_Right", "Intersections").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Intersections> RightIntersectionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Intersections>("KazMap.DataAccess.FK_Path_Right", "Intersections");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Intersections>("KazMap.DataAccess.FK_Path_Right", "Intersections", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_Path_LeftNode", "Nodes")]
        public Nodes LeftNode
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nodes>("KazMap.DataAccess.FK_Path_LeftNode", "Nodes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nodes>("KazMap.DataAccess.FK_Path_LeftNode", "Nodes").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Nodes> LeftNodeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nodes>("KazMap.DataAccess.FK_Path_LeftNode", "Nodes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Nodes>("KazMap.DataAccess.FK_Path_LeftNode", "Nodes", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_Path_RightNode", "Nodes")]
        public Nodes RightNode
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nodes>("KazMap.DataAccess.FK_Path_RightNode", "Nodes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nodes>("KazMap.DataAccess.FK_Path_RightNode", "Nodes").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Nodes> RightNodeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nodes>("KazMap.DataAccess.FK_Path_RightNode", "Nodes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Nodes>("KazMap.DataAccess.FK_Path_RightNode", "Nodes", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_Path_Road", "Roads")]
        public Roads Road
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Roads>("KazMap.DataAccess.FK_Path_Road", "Roads").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Roads>("KazMap.DataAccess.FK_Path_Road", "Roads").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Roads> RoadReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Roads>("KazMap.DataAccess.FK_Path_Road", "Roads");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Roads>("KazMap.DataAccess.FK_Path_Road", "Roads", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KazMap.DataAccess", Name="RelationNodes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RelationNodes : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта RelationNodes.
        /// </summary>
        /// <param name="id">Исходное значение свойства Id.</param>
        public static RelationNodes CreateRelationNodes(global::System.Int64 id)
        {
            RelationNodes relationNodes = new RelationNodes();
            relationNodes.Id = id;
            return relationNodes;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RelationId
        {
            get
            {
                return _RelationId;
            }
            set
            {
                OnRelationIdChanging(value);
                ReportPropertyChanging("RelationId");
                _RelationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RelationId");
                OnRelationIdChanged();
            }
        }
        private Nullable<global::System.Int64> _RelationId;
        partial void OnRelationIdChanging(Nullable<global::System.Int64> value);
        partial void OnRelationIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ItemId
        {
            get
            {
                return _ItemId;
            }
            set
            {
                OnItemIdChanging(value);
                ReportPropertyChanging("ItemId");
                _ItemId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ItemId");
                OnItemIdChanged();
            }
        }
        private Nullable<global::System.Int64> _ItemId;
        partial void OnItemIdChanging(Nullable<global::System.Int64> value);
        partial void OnItemIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Position
        {
            get
            {
                return _Position;
            }
            set
            {
                OnPositionChanging(value);
                ReportPropertyChanging("Position");
                _Position = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Position");
                OnPositionChanged();
            }
        }
        private Nullable<global::System.Int32> _Position;
        partial void OnPositionChanging(Nullable<global::System.Int32> value);
        partial void OnPositionChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> TypeId
        {
            get
            {
                return _TypeId;
            }
            set
            {
                OnTypeIdChanging(value);
                ReportPropertyChanging("TypeId");
                _TypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TypeId");
                OnTypeIdChanged();
            }
        }
        private Nullable<global::System.Int64> _TypeId;
        partial void OnTypeIdChanging(Nullable<global::System.Int64> value);
        partial void OnTypeIdChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_RelNODE_Relation", "Relations")]
        public Relations Relation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Relations>("KazMap.DataAccess.FK_RelNODE_Relation", "Relations").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Relations>("KazMap.DataAccess.FK_RelNODE_Relation", "Relations").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Relations> RelationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Relations>("KazMap.DataAccess.FK_RelNODE_Relation", "Relations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Relations>("KazMap.DataAccess.FK_RelNODE_Relation", "Relations", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KazMap.DataAccess", Name="Relations")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Relations : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Relations.
        /// </summary>
        /// <param name="relationId">Исходное значение свойства RelationId.</param>
        public static Relations CreateRelations(global::System.Int64 relationId)
        {
            Relations relations = new Relations();
            relations.RelationId = relationId;
            return relations;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 RelationId
        {
            get
            {
                return _RelationId;
            }
            set
            {
                if (_RelationId != value)
                {
                    OnRelationIdChanging(value);
                    ReportPropertyChanging("RelationId");
                    _RelationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RelationId");
                    OnRelationIdChanged();
                }
            }
        }
        private global::System.Int64 _RelationId;
        partial void OnRelationIdChanging(global::System.Int64 value);
        partial void OnRelationIdChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_RelNODE_Relation", "RelationNodes")]
        public EntityCollection<RelationNodes> Nodes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RelationNodes>("KazMap.DataAccess.FK_RelNODE_Relation", "RelationNodes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RelationNodes>("KazMap.DataAccess.FK_RelNODE_Relation", "RelationNodes", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_RelTAG_Relation", "RelationTags")]
        public EntityCollection<RelationTags> Tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<RelationTags>("KazMap.DataAccess.FK_RelTAG_Relation", "RelationTags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<RelationTags>("KazMap.DataAccess.FK_RelTAG_Relation", "RelationTags", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KazMap.DataAccess", Name="RelationTags")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RelationTags : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта RelationTags.
        /// </summary>
        /// <param name="id">Исходное значение свойства Id.</param>
        public static RelationTags CreateRelationTags(global::System.Int64 id)
        {
            RelationTags relationTags = new RelationTags();
            relationTags.Id = id;
            return relationTags;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RelationId
        {
            get
            {
                return _RelationId;
            }
            set
            {
                OnRelationIdChanging(value);
                ReportPropertyChanging("RelationId");
                _RelationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RelationId");
                OnRelationIdChanged();
            }
        }
        private Nullable<global::System.Int64> _RelationId;
        partial void OnRelationIdChanging(Nullable<global::System.Int64> value);
        partial void OnRelationIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> TypeId
        {
            get
            {
                return _TypeId;
            }
            set
            {
                OnTypeIdChanging(value);
                ReportPropertyChanging("TypeId");
                _TypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TypeId");
                OnTypeIdChanged();
            }
        }
        private Nullable<global::System.Int64> _TypeId;
        partial void OnTypeIdChanging(Nullable<global::System.Int64> value);
        partial void OnTypeIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_RelTAG_Relation", "Relations")]
        public Relations Relation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Relations>("KazMap.DataAccess.FK_RelTAG_Relation", "Relations").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Relations>("KazMap.DataAccess.FK_RelTAG_Relation", "Relations").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Relations> RelationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Relations>("KazMap.DataAccess.FK_RelTAG_Relation", "Relations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Relations>("KazMap.DataAccess.FK_RelTAG_Relation", "Relations", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_RelTAG_TagType", "TagTypes")]
        public TagTypes Type
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TagTypes>("KazMap.DataAccess.FK_RelTAG_TagType", "TagTypes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TagTypes>("KazMap.DataAccess.FK_RelTAG_TagType", "TagTypes").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TagTypes> TypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TagTypes>("KazMap.DataAccess.FK_RelTAG_TagType", "TagTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TagTypes>("KazMap.DataAccess.FK_RelTAG_TagType", "TagTypes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KazMap.DataAccess", Name="Roads")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Roads : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Roads.
        /// </summary>
        /// <param name="id">Исходное значение свойства Id.</param>
        public static Roads CreateRoads(global::System.Int64 id)
        {
            Roads roads = new Roads();
            roads.Id = id;
            return roads;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> WayId
        {
            get
            {
                return _WayId;
            }
            set
            {
                OnWayIdChanging(value);
                ReportPropertyChanging("WayId");
                _WayId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WayId");
                OnWayIdChanged();
            }
        }
        private Nullable<global::System.Int64> _WayId;
        partial void OnWayIdChanging(Nullable<global::System.Int64> value);
        partial void OnWayIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaxSpeed
        {
            get
            {
                return _MaxSpeed;
            }
            set
            {
                OnMaxSpeedChanging(value);
                ReportPropertyChanging("MaxSpeed");
                _MaxSpeed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxSpeed");
                OnMaxSpeedChanged();
            }
        }
        private Nullable<global::System.Int32> _MaxSpeed;
        partial void OnMaxSpeedChanging(Nullable<global::System.Int32> value);
        partial void OnMaxSpeedChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_Road_Way", "Ways")]
        public Ways Way
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ways>("KazMap.DataAccess.FK_Road_Way", "Ways").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ways>("KazMap.DataAccess.FK_Road_Way", "Ways").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ways> WayReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ways>("KazMap.DataAccess.FK_Road_Way", "Ways");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ways>("KazMap.DataAccess.FK_Road_Way", "Ways", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KazMap.DataAccess", Name="TagTypes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TagTypes : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта TagTypes.
        /// </summary>
        /// <param name="id">Исходное значение свойства Id.</param>
        public static TagTypes CreateTagTypes(global::System.Int64 id)
        {
            TagTypes tagTypes = new TagTypes();
            tagTypes.Id = id;
            return tagTypes;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KazMap.DataAccess", Name="WayNodes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WayNodes : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта WayNodes.
        /// </summary>
        /// <param name="id">Исходное значение свойства Id.</param>
        public static WayNodes CreateWayNodes(global::System.Int64 id)
        {
            WayNodes wayNodes = new WayNodes();
            wayNodes.Id = id;
            return wayNodes;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> WayId
        {
            get
            {
                return _WayId;
            }
            set
            {
                OnWayIdChanging(value);
                ReportPropertyChanging("WayId");
                _WayId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WayId");
                OnWayIdChanged();
            }
        }
        private Nullable<global::System.Int64> _WayId;
        partial void OnWayIdChanging(Nullable<global::System.Int64> value);
        partial void OnWayIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> NodeId
        {
            get
            {
                return _NodeId;
            }
            set
            {
                OnNodeIdChanging(value);
                ReportPropertyChanging("NodeId");
                _NodeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NodeId");
                OnNodeIdChanged();
            }
        }
        private Nullable<global::System.Int64> _NodeId;
        partial void OnNodeIdChanging(Nullable<global::System.Int64> value);
        partial void OnNodeIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Position
        {
            get
            {
                return _Position;
            }
            set
            {
                OnPositionChanging(value);
                ReportPropertyChanging("Position");
                _Position = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Position");
                OnPositionChanged();
            }
        }
        private Nullable<global::System.Int32> _Position;
        partial void OnPositionChanging(Nullable<global::System.Int32> value);
        partial void OnPositionChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_WayNODE_NODE", "Nodes")]
        public Nodes Node
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nodes>("KazMap.DataAccess.FK_WayNODE_NODE", "Nodes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nodes>("KazMap.DataAccess.FK_WayNODE_NODE", "Nodes").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Nodes> NodeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nodes>("KazMap.DataAccess.FK_WayNODE_NODE", "Nodes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Nodes>("KazMap.DataAccess.FK_WayNODE_NODE", "Nodes", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_WayNODE_Way", "Ways")]
        public Ways Way
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ways>("KazMap.DataAccess.FK_WayNODE_Way", "Ways").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ways>("KazMap.DataAccess.FK_WayNODE_Way", "Ways").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ways> WayReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ways>("KazMap.DataAccess.FK_WayNODE_Way", "Ways");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ways>("KazMap.DataAccess.FK_WayNODE_Way", "Ways", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KazMap.DataAccess", Name="Ways")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ways : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Ways.
        /// </summary>
        /// <param name="wayId">Исходное значение свойства WayId.</param>
        public static Ways CreateWays(global::System.Int64 wayId)
        {
            Ways ways = new Ways();
            ways.WayId = wayId;
            return ways;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 WayId
        {
            get
            {
                return _WayId;
            }
            set
            {
                if (_WayId != value)
                {
                    OnWayIdChanging(value);
                    ReportPropertyChanging("WayId");
                    _WayId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WayId");
                    OnWayIdChanged();
                }
            }
        }
        private global::System.Int64 _WayId;
        partial void OnWayIdChanging(global::System.Int64 value);
        partial void OnWayIdChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_WayNODE_Way", "WayNodes")]
        public EntityCollection<WayNodes> Nodes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WayNodes>("KazMap.DataAccess.FK_WayNODE_Way", "WayNodes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WayNodes>("KazMap.DataAccess.FK_WayNODE_Way", "WayNodes", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_WayTAG_Way", "WayTags")]
        public EntityCollection<WayTags> Tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WayTags>("KazMap.DataAccess.FK_WayTAG_Way", "WayTags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WayTags>("KazMap.DataAccess.FK_WayTAG_Way", "WayTags", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_Road_Way", "Roads")]
        public EntityCollection<Roads> Road
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Roads>("KazMap.DataAccess.FK_Road_Way", "Roads");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Roads>("KazMap.DataAccess.FK_Road_Way", "Roads", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="KazMap.DataAccess", Name="WayTags")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WayTags : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта WayTags.
        /// </summary>
        /// <param name="id">Исходное значение свойства Id.</param>
        public static WayTags CreateWayTags(global::System.Int64 id)
        {
            WayTags wayTags = new WayTags();
            wayTags.Id = id;
            return wayTags;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> WayId
        {
            get
            {
                return _WayId;
            }
            set
            {
                OnWayIdChanging(value);
                ReportPropertyChanging("WayId");
                _WayId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WayId");
                OnWayIdChanged();
            }
        }
        private Nullable<global::System.Int64> _WayId;
        partial void OnWayIdChanging(Nullable<global::System.Int64> value);
        partial void OnWayIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> TypeId
        {
            get
            {
                return _TypeId;
            }
            set
            {
                OnTypeIdChanging(value);
                ReportPropertyChanging("TypeId");
                _TypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TypeId");
                OnTypeIdChanged();
            }
        }
        private Nullable<global::System.Int64> _TypeId;
        partial void OnTypeIdChanging(Nullable<global::System.Int64> value);
        partial void OnTypeIdChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_WayTAG_TagType", "TagTypes")]
        public TagTypes Type
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TagTypes>("KazMap.DataAccess.FK_WayTAG_TagType", "TagTypes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TagTypes>("KazMap.DataAccess.FK_WayTAG_TagType", "TagTypes").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TagTypes> TypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TagTypes>("KazMap.DataAccess.FK_WayTAG_TagType", "TagTypes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TagTypes>("KazMap.DataAccess.FK_WayTAG_TagType", "TagTypes", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("KazMap.DataAccess", "FK_WayTAG_Way", "Ways")]
        public Ways Way
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ways>("KazMap.DataAccess.FK_WayTAG_Way", "Ways").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ways>("KazMap.DataAccess.FK_WayTAG_Way", "Ways").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ways> WayReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ways>("KazMap.DataAccess.FK_WayTAG_Way", "Ways");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ways>("KazMap.DataAccess.FK_WayTAG_Way", "Ways", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
